# SPDX-License-Identifier: MIT
#
# Copyright (C) 2021-2026 LIKE2000-ART
#
# This is free software, licensed under the MIT License.
#
include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-picoclaw
PKG_VERSION:=1.0.0
PKG_RELEASE:=20260226

PKG_MAINTAINER:=LIKE2000-ART
PKG_CONFIG_DEPENDS:=

LUCI_TITLE:=LuCI Support for PicoClaw AI Assistant
LUCI_DEPENDS:=+picoclaw
LUCI_PKGARCH:=all



include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
